### ISSUE TITLE
Broken Path for generated files - Same Folder dest and src (0.3.0)

### ISSUE THREAD

**Issue by martincaron** [project-collins/grunt-csssplit#16]
In 0.3.0, the generated files are not created in the path specified by the dest param.

See config below. The was working with in 0.2.4 with same config.

csssplit: {
            css_target: {
                src: ['<%= config.cssSrc %>/style.css'],
                dest: '<%= config.cssSrc %>/',
                options: {
                    maxSelectors: 4095,
                    maxPages: 10,
                    suffix: '_page_'
                }
            }
        }

Instead of files being generated here :  <%= config.cssSrc %>
They were generated here : <%= config.cssSrc %>../css_page

**Comment by robotlovesyou** [comment]
I'm pretty sure that if the output path were broken then the tests would be broken too, and they run just fine for me.

**Comment by martincaron** [comment]
Indeed tests all passed.

The particular issue seems related to how the params are interpreted when trying to output the split files into the same directory as the source.

A test expecting the split files outputted in the same directory as source could maybe have caught this.

That being said, we managed to get around it in 0.3.0 by specifying the current working directory and modifying src and dest :

cwd : '<%= config.cssSrc %>'
src : 'style.css'
dest : '<%= config.cssSrc %>'

This solution does not play well with the previous version though (0.2.4). To output split files in the same folder as src in 0.2.4, use : 

src : '<%= config.cssSrc %>/style.css'
dest : '<%= config.cssSrc %>/'

**Comment by vict-shevchenko** [comment]
+1

**Comment by MarcDula** [comment]
I had this issue with version 0.4.0 and was able to get it working by reading the documentation here: http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

In my case, I ended up with:
```javascript
csssplit: {
  dev: {
    expand: true,
    cwd: 'src',
    src: ['assets/css/global.css'],
    dest: 'src',
    options: {
      maxSelectors: 4095,
      suffix: '_ie_'
    }
  }
}
```
This reads in ```src/assets/css/global.css``` and outputs ```src/assets/css/global_ie_1.css```, ```src/assets/css/global_ie_2.css```, and so on.

**Comment by vict-shevchenko** [comment]
Unfortunatelly your solution does not work for me.

Here is my config, that is also valid according to grunt docs:

```
dev: {
	src: '<%= buildFolder %>/styles/css/main.css',
	dest: '<%= buildFolder %>/styles/css/',
	options: {
		maxSelectors: 4095,
		maxPages: 2,
		suffix: '-bundle-'
	}
}
```

**Comment by jamesckemp** [comment]
I had to do mine like this:

```
csssplit: {
    dev: {
        expand: false,
        src: ['<%= dirs.assets %>/css/styles.css'],
        dest: '<%= dirs.assets %>/css/styles.css',
        options: {
            maxSelectors: 4095,
            maxPages: 3,
            suffix: '-split-'
        }
    },
},
```

Otherwise it wasn't creating the files correctly. This creates styles-split-1.css in the correct directory.
